apiVersion: v1
kind: Service
metadata:
  name: bitcoind
  namespace: bitcoin-node
spec:
  selector:
    app: bitcoind
  type: LoadBalancer
  ports:
    - protocol: TCP
      name: http
      port: 8332
      targetPort: 8332
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    service: bitcoind
  name: bitcoind
  namespace: bitcoin-node
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: bitcoind-resources
  namespace: bitcoin-node
spec:
  hard:
    pods: "40"
    requests.cpu: "40"
    requests.memory: 128Gi
    limits.cpu: "80"
    limits.memory: 256Gi
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: bitcoind-hpa
  namespace: bitcoin-node
spec:
  maxReplicas: 40
  minReplicas: 1
  scaleTargetRef:
    apiVersion: apps/v1
    kind: StatefulSet
    name: bitcoind
  targetCPUUtilizationPercentage: 80
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: multi-port-egress
  namespace: bitcoin-node
spec:
  podSelector:
    matchLabels:
      role: db
  policyTypes:
    - Egress
  egress:
    - ports:
        - protocol: TCP
          port: 8332
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: bitcoind
  namespace: bitcoin-node
spec:
  capacity:
    storage: 800Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: bitcoind
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: bitcoind
  namespace: bitcoin-node
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 800Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: bitcoind
  namespace: bitcoin-node
spec:
  serviceName: bitcoind
  replicas: 1
  selector:
    matchLabels:
      app: bitcoind
  template:
    metadata:
      labels:
        app: bitcoind
    spec:
      serviceAccountName: bitcoind
      restartPolicy: Always
      securityContext:
        readOnlyRootFilesystem: true
        runAsNonRoot: true

        # seccomp and apparmor additional security profiles to harden your kubernetes workloads https://kubernetes.io/docs/tutorials/security/apparmor/ https://kubernetes.io/docs/tutorials/security/seccomp/
        seccompProfile: 
          type: RuntimeDefault
        appArmorProfile:
          type: RuntimeDefault
      containers:
        - name: bitcoind
          image: bitoind:linux
          ports:
          - containerPort: 8334
          # liveness probe example from https://github.com/ompldr/kubernetes/blob/master/bitcoind-us-west1.yaml
          readinessProbe:
            tcpSocket:
              port: 8332
            initialDelaySeconds: 120
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 8332
            initialDelaySeconds: 120
            periodSeconds: 5
          volumeMounts:
            - name: bitcoind
              mountPath: /root/.bitcoin
  volumeClaimTemplates:
    - metadata:
        name: bitcoind
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: default
        resources:
          requests:
            storage: 800Gi